--- # ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo-service
#   labels:
#     app: mongo
# spec:
#   selector:
#     app: mongo
#     role: mongo
#   # clusterIP: None
#   ports:
#     - port: 27017
#       targetPort: 27017
#   type: LoadBalancer
apiVersion: v1
kind: Service
metadata:
  name: mongo-service-headless
spec:
  selector:
    role: mongo
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
