version = 0.1
[default.deploy.parameters]
stack_name = "csgy9223-hw3-stack"
resolve_s3 = true
s3_prefix = "csgy9223-hw3-stack"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "Namespace=\"default\""
