AWSTemplateFormatVersion: "2010-09-09"

Description: Parent stack for the CSGY 9223-a HW3 k8 clustet
# Available top-level fields are listed in code completion

# Add Resources Here: uncomment the following lines
# Resources:
#   <resource name here>:
#     Type: # resource type here - available resources are listed in code completion
#     # <add resource-specific properties underneath this entry  - available properties are listed in code completion>
#     Properties:
