AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Parent stack for the CSGY 9223-a HW3 k8 cluster
# Available top-level fields are listed in code completion

Resources:
  # Prometheus:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: prometheus/template.yml
  #     Parameters:
  #       KubeClusterName: !Ref EKSControlPane
  #       Namespace: !GetAtt EKSControlPane.Outputs.Namespace

  # EKSControlPane:
  #   Type: AWS::Serverless::Application
  #   Properties:
  #     Location: eks/template.yml
  #     Parameters:
  #       SecurityGroup: !GetAtt VPCStack.Outputs.SecurityGroup
  #       Subnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
  #       Subnet2: !GetAtt VPCStack.Outputs.PublicSubnet2

  VPCStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: vpc/template.yml

Outputs:
  VPCName:
    Value: !GetAtt VPCStack.Outputs.VPC
  # ClusterEndpoint:
  #   Value: !GetAtt EKSControlPane.Outputs.Endpoint
