apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-deployment
  template:
    metadata:
      labels:
        app: webapp-deployment
    spec:
      containers:
        - name: webapp-deployment
          image: ab7289/csgy9223-cloud-computing:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000
              name: webapp-int-port
          env:
            - name: PORT
              value: "5000"
            - name: FLASK_ENV
              value: development
            - name: MONGO_SERVICE_SERVICE_HOST
              value: "mongo-1.mongo-service-headless.default.svc.cluster.local"
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "1"
