apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp-deployment
  ports:
    - port: 8080
      targetPort: webapp-int-port
      protocol: TCP
  type: LoadBalancer
